CREATE TABLE Cars (
    id INT PRIMARY KEY AUTO_INCREMENT,
    user_id INT,
    model VARCHAR(255),
    fuel VARCHAR(255),
    manufacturer VARCHAR(255),
    color VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
